// normal_dist.proto
// protoc --go_out=. normal_dist.proto
// protoc --go-grpc_out=. normal_dist.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: normal_dist.proto

package go_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PiRequest) Reset() {
	*x = PiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_normal_dist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PiRequest) ProtoMessage() {}

func (x *PiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_normal_dist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PiRequest.ProtoReflect.Descriptor instead.
func (*PiRequest) Descriptor() ([]byte, []int) {
	return file_normal_dist_proto_rawDescGZIP(), []int{0}
}

type PiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PiResponse) Reset() {
	*x = PiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_normal_dist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PiResponse) ProtoMessage() {}

func (x *PiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_normal_dist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PiResponse.ProtoReflect.Descriptor instead.
func (*PiResponse) Descriptor() ([]byte, []int) {
	return file_normal_dist_proto_rawDescGZIP(), []int{1}
}

func (x *PiResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ExpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
}

func (x *ExpRequest) Reset() {
	*x = ExpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_normal_dist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpRequest) ProtoMessage() {}

func (x *ExpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_normal_dist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpRequest.ProtoReflect.Descriptor instead.
func (*ExpRequest) Descriptor() ([]byte, []int) {
	return file_normal_dist_proto_rawDescGZIP(), []int{2}
}

func (x *ExpRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

type ExpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ExpResponse) Reset() {
	*x = ExpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_normal_dist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpResponse) ProtoMessage() {}

func (x *ExpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_normal_dist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpResponse.ProtoReflect.Descriptor instead.
func (*ExpResponse) Descriptor() ([]byte, []int) {
	return file_normal_dist_proto_rawDescGZIP(), []int{3}
}

func (x *ExpResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_normal_dist_proto protoreflect.FileDescriptor

var file_normal_dist_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x0b, 0x0a, 0x09, 0x50, 0x69, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x22, 0x0a, 0x0a, 0x50, 0x69, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1a, 0x0a, 0x0a, 0x45, 0x78,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x22, 0x23, 0x0a, 0x0b, 0x45, 0x78, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x7b, 0x0a, 0x12, 0x4e,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x30, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x69,
	0x12, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0c, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x45, 0x78, 0x70, 0x12, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45, 0x78, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45, 0x78, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x67, 0x6f, 0x2d,
	0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_normal_dist_proto_rawDescOnce sync.Once
	file_normal_dist_proto_rawDescData = file_normal_dist_proto_rawDesc
)

func file_normal_dist_proto_rawDescGZIP() []byte {
	file_normal_dist_proto_rawDescOnce.Do(func() {
		file_normal_dist_proto_rawDescData = protoimpl.X.CompressGZIP(file_normal_dist_proto_rawDescData)
	})
	return file_normal_dist_proto_rawDescData
}

var file_normal_dist_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_normal_dist_proto_goTypes = []interface{}{
	(*PiRequest)(nil),   // 0: main.PiRequest
	(*PiResponse)(nil),  // 1: main.PiResponse
	(*ExpRequest)(nil),  // 2: main.ExpRequest
	(*ExpResponse)(nil), // 3: main.ExpResponse
}
var file_normal_dist_proto_depIdxs = []int32{
	0, // 0: main.NormalDistribution.CalculatePi:input_type -> main.PiRequest
	2, // 1: main.NormalDistribution.CalculateExp:input_type -> main.ExpRequest
	1, // 2: main.NormalDistribution.CalculatePi:output_type -> main.PiResponse
	3, // 3: main.NormalDistribution.CalculateExp:output_type -> main.ExpResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_normal_dist_proto_init() }
func file_normal_dist_proto_init() {
	if File_normal_dist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_normal_dist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_normal_dist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_normal_dist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_normal_dist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_normal_dist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_normal_dist_proto_goTypes,
		DependencyIndexes: file_normal_dist_proto_depIdxs,
		MessageInfos:      file_normal_dist_proto_msgTypes,
	}.Build()
	File_normal_dist_proto = out.File
	file_normal_dist_proto_rawDesc = nil
	file_normal_dist_proto_goTypes = nil
	file_normal_dist_proto_depIdxs = nil
}
